/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern void ITM_SendChar(uint8_t ch);

#define TASK_STACK_SIZE 1024U
#define SCHED_STACK_SIZE 1024U

#define RAM_START 0x20000000U
#define RAM_SIZE (20U * 1024U)
#define RAM_END (RAM_START + RAM_SIZE)

#define SCHED_STACK_START (RAM_END)
#define IDLE_STACK_START (RAM_END - TASK_STACK_SIZE)
#define T1_STACK_START (RAM_END - 2 * TASK_STACK_SIZE)
#define T2_STACK_START (RAM_END - 3 * TASK_STACK_SIZE)
#define T3_STACK_START (RAM_END -4 * TASK_STACK_SIZE)
#define T4_STACK_START (RAM_END - 5 * TASK_STACK_SIZE)

#define TICK_FREQ			1000u
#define HSI_CLOCK			8000000u
#define SYSTICK_CLK			HSI_CLOCK

#define MAX_TASKS 5

#define RUNNING_STATE 0x00
#define BLOCKED_STATE 0xFF

#define DUMMY_XPSR 0x01000000

void idle_task(void);
void task_1(void);
void task_2(void);
void task_3(void);
void task_4(void);

void OsKernelInit(void);
void OsCreateTask(void (*handler)(void));
void SysTick_Init(uint32_t freq);
__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_stack);
void init_tasks_stack(void);
void enable_processor_fault();
__attribute__((naked)) void switch_sp_to_psp(void);
void task_delay(uint32_t tick_count);

uint8_t current_task = 1;
uint32_t g_tick_count;

typedef struct {
	uint32_t id;
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t current_state;
	void (*task_handler)(void);
} TCB_t;

TCB_t user_tasks[MAX_TASKS];
uint32_t memPoolBitset = 0;

int main(void)
{
//	enable_processor_fault();
//	init_scheduler_stack(SCHED_STACK_START);
	OsKernelInit();

//	init_tasks_stack();
	OsCreateTask(task_1);
	OsCreateTask(task_2);
	OsCreateTask(task_3);
	OsCreateTask(task_4);

	switch_sp_to_psp();

	task_1();
	for(;;);
}

void idle_task(void) {
	while(1);
}

void task_1(void) {
	while(1) {
		printf("Task 1\n");
		task_delay(1000);
	}
}

void task_2(void) {
	while(1) {
		printf("Task 2\n");
		task_delay(2000);
	}
}

void task_3(void) {
	while(1) {
		printf("Task 3\n");
		task_delay(4000);
	}
}

void task_4(void) {
	while(1) {
		printf("Task 4\n");
		task_delay(8000);
	}
}

void OsKernelInit() {
	enable_processor_fault();
//	init_scheduler_stack(SCHED_STACK_START);
	OsCreateTask(idle_task);
	SysTick_Init(TICK_FREQ);
}

void OsCreateTask(void (*handler)(void)) {
	// Get the unallocated ID
	uint32_t taskID = 0;
	uint32_t *psp;

	for (uint8_t i = 0; i < MAX_TASKS; i++) {
		if ((memPoolBitset & (1 << (31 - i))) == 0) {
			taskID = i;
			memPoolBitset |= (1 << (31 - i));
			break;
		}
	}
	user_tasks[taskID].id = taskID;
	user_tasks[taskID].task_handler = handler;
	user_tasks[taskID].current_state = RUNNING_STATE;
	user_tasks[taskID].psp_value = IDLE_STACK_START - taskID * 1024;

	// Init task's stack
	psp = (uint32_t *)user_tasks[taskID].psp_value;
	psp--;
	*psp = DUMMY_XPSR; //0x01000000

	psp--; // PC
	*psp = (uint32_t)user_tasks[taskID].task_handler;

	psp--; //LR
	*psp = 0xFFFFFFFD;

	for(int j = 0; j <13; j++) {
		psp--;
		*psp = 0;
	}

	user_tasks[taskID].psp_value = (uint32_t)psp;
}

void yield(void) {
	uint32_t *ICSR = (uint32_t*)0xE000ED04;

	*ICSR |= (1 << 28);
}

void task_delay(uint32_t tick_count) {
	if(current_task) {
		user_tasks[current_task].block_count = g_tick_count + tick_count;
		user_tasks[current_task].current_state = BLOCKED_STATE;
		yield();
	}
}

void SysTick_Init(uint32_t freq) {
	uint32_t *pSYST_RVR = (uint32_t *)0xE000E014;
	uint32_t *pSYST_CSR = (uint32_t *)0xE000E010;
	uint32_t reloadValue = SYSTICK_CLK / freq - 1;

	// Clear data
	*pSYST_RVR &= ~(0x00FFFFFF);
	// Load reload value
	*pSYST_RVR = reloadValue;
	*pSYST_CSR |= (1 << 1);
	*pSYST_CSR |= (1 << 2);
	*pSYST_CSR |= (1 << 0);

}

__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_stack) {
	__asm volatile("MSR MSP,%0": : "r" (sched_top_stack) : );
	__asm volatile("BX LR");
}


void init_tasks_stack(void) {
	uint32_t *psp;

	user_tasks[0].current_state = RUNNING_STATE;
	user_tasks[1].current_state = RUNNING_STATE;
	user_tasks[2].current_state = RUNNING_STATE;
	user_tasks[3].current_state = RUNNING_STATE;
	user_tasks[4].current_state = RUNNING_STATE;

	user_tasks[0].psp_value = IDLE_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;

	user_tasks[0].task_handler = idle_task;
	user_tasks[1].task_handler = task_1;
	user_tasks[2].task_handler = task_2;
	user_tasks[3].task_handler = task_3;
	user_tasks[4].task_handler = task_4;

	for(int i = 0; i < MAX_TASKS; i++) {
		psp = (uint32_t *)user_tasks[i].psp_value;

		psp--;
		*psp = DUMMY_XPSR; //0x01000000

		psp--; // PC
		*psp = (uint32_t)user_tasks[i].task_handler;

		psp--; //LR
		*psp = 0xFFFFFFFD;

		for(int j = 0; j <13; j++) {
			psp--;
			*psp = 0;
		}

		user_tasks[i].psp_value = (uint32_t)psp;

	}
}

void enable_processor_fault() {
	uint32_t *SHCSR = (uint32_t*)0xE000ED24;

	*SHCSR |= (1 << 16);
	*SHCSR |= (1 << 17);
	*SHCSR |= (1 << 18);

}

uint32_t get_psp_value(void) {
	return user_tasks[current_task].psp_value;
}

__attribute__((naked)) void switch_sp_to_psp(void) {
	//init psp with task1 stack start
	__asm volatile ("PUSH {LR}"); //save LR to main function
	__asm volatile ("BL get_psp_value"); //this call corrupts LR
	__asm volatile ("MSR PSP,R0"); // init psp
	__asm volatile ("POP {LR}"); // get main() LR back

	// change sp to psp
	__asm volatile ("MOV R0,#0x02");
	__asm volatile ("MSR CONTROL,R0");
	__asm volatile ("BX LR");
}

void save_psp_value(uint32_t current_psp_value) {
	user_tasks[current_task].psp_value = current_psp_value;
}

void update_next_task(void) {
	int state = BLOCKED_STATE;

	for(int i = 0; i < MAX_TASKS; i++) {
		current_task++;
		current_task %= MAX_TASKS;
		state = user_tasks[current_task].current_state;
		if((state == RUNNING_STATE) && (current_task != 0))
			break;
	}

	if(state != RUNNING_STATE)
		current_task = 0;
}

void unblock_tasks(void) {
	for(int i = 1; i < MAX_TASKS; i++) {
		if (user_tasks[i].current_state != RUNNING_STATE) {
			if (user_tasks[i].block_count == g_tick_count) {
				user_tasks[i].current_state = RUNNING_STATE;
			}
		}
	}
}

void SysTick_Handler(void) {
	g_tick_count++;
	unblock_tasks();
	yield();
}

__attribute__((naked)) void PendSV_Handler(void) {
	// save the context of current task
	__asm volatile ("MRS R0,PSP"); //get current task's psp
	__asm volatile ("STMDB R0!,{R4-R11}"); // using psp store sf2 (r4-r11)
	__asm volatile ("PUSH {LR}");
	__asm volatile ("BL save_psp_value");

	// retrieve the context of the next task
	__asm volatile ("BL update_next_task");//select next task
	__asm volatile ("BL get_psp_value"); // get next task's psp
	__asm volatile ("LDMIA R0!,{R4-R11}"); // retrieve R4-r11
	__asm volatile ("MSR PSP,R0");
	__asm volatile ("POP {LR}");
	__asm volatile ("BX LR");
}

void delay(uint32_t count) {
	for(uint32_t i = 0; i < count; i++);
}

void HardFault_Handler(void) {
	printf("Exception: Hardfault\n");
	while(1);
}

void MemManage_Handler(void) {
	printf("Exception: MemFault\n");
	while(1);
}

void BusFault_Handler(void) {
	printf("Exception: BusFault\n");
	while(1);
}












