/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <os_kernel.h>
#include <os_queue_utils.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern void ITM_SendChar(uint8_t ch);

#define TASK_STACK_SIZE 1024U
#define SCHED_STACK_SIZE 1024U

#define RAM_START 0x20000000U
#define RAM_SIZE (20U * 1024U)
#define RAM_END (RAM_START + RAM_SIZE)

#define SCHED_STACK_START (RAM_END)
#define IDLE_STACK_START (RAM_END - TASK_STACK_SIZE)
#define T1_STACK_START (RAM_END - 2 * TASK_STACK_SIZE)
#define T2_STACK_START (RAM_END - 3 * TASK_STACK_SIZE)
#define T3_STACK_START (RAM_END -4 * TASK_STACK_SIZE)
#define T4_STACK_START (RAM_END - 5 * TASK_STACK_SIZE)

#define TICK_FREQ			1000u
#define HSI_CLOCK			8000000u
#define SYSTICK_CLK			HSI_CLOCK

#define RUNNING_STATE 0x00
#define BLOCKED_STATE 0xFF

#define DUMMY_XPSR 0x01000000

void idle_task(void);
void task_1(void);
void task_2(void);
void task_3(void);
void task_4(void);

void OsKernelInit(void);
void OsCreateTask(void (*handler)(void), uint8_t priority);
void OsStartScheduler(void);
void SysTick_Init(uint32_t freq);
void enable_processor_fault();
__attribute__((naked)) void switch_sp_to_psp(void);
void task_delay(uint32_t tick_count);

uint8_t current_task = 1;
uint32_t g_tick_count;
uint8_t numberCreatedTask = 0;

TCB_t user_tasks[MAX_TASKS];
uint32_t memPoolBitset = 0;
MaxHeap taskQueue;

int main(void)
{
	OsKernelInit();

	OsCreateTask(task_1, 1);
//	OsCreateTask(task_2);
//	OsCreateTask(task_3);
	OsCreateTask(task_4, 1);

	OsStartScheduler();
	for(;;);
}

void idle_task(void) {
	while(1);
}

void task_1(void) {
	while(1) {
		printf("Task 1\n");
//		task_delay(1000);
	}
}

void task_2(void) {
	while(1) {
		printf("Task 2\n");
		task_delay(2000);
	}
}

void task_3(void) {
	while(1) {
		printf("Task 3\n");
		task_delay(4000);
	}
}

void task_4(void) {
	while(1) {
		printf("Task 4\n");
//		task_delay(8000);
	}
}

void OsKernelInit() {
	enable_processor_fault();
	OsHeapInit(&taskQueue);
	OsCreateTask(idle_task, 0);
	SysTick_Init(TICK_FREQ);
}

void OsCreateTask(void (*handler)(void), uint8_t priority) {
	// Get the unallocated ID
	uint32_t taskID = 0;
	uint32_t *psp;
	TCB_t *newTask;

	for (uint8_t i = 0; i < MAX_TASKS; i++) {
		if ((memPoolBitset & (1 << (31 - i))) == 0) {
			numberCreatedTask++;
			taskID = i;
			memPoolBitset |= (1 << (31 - i));
			break;
		}
	}
	newTask = (TCB_t *)malloc(sizeof(TCB_t));
	newTask->id = taskID;
	newTask->task_handler = handler;
	newTask->current_state = RUNNING_STATE;
	newTask->psp_value = IDLE_STACK_START - taskID * 1024;
	newTask->priority = priority;

	// Init task's stack
	psp = (uint32_t *)newTask->psp_value;
	psp--;
	*psp = DUMMY_XPSR; //0x01000000

	psp--; // PC
	*psp = (uint32_t)newTask->task_handler;

	psp--; //LR
	*psp = 0xFFFFFFFD;

	for(int j = 0; j <13; j++) {
		psp--;
		*psp = 0;
	}

	newTask->psp_value = (uint32_t)psp;
	OsHeapInsert(&taskQueue, newTask);
}

void OsStartScheduler(void) {
	TCB_t *task;

	switch_sp_to_psp();
	task = OsHeapPeek(&taskQueue);
	task->task_handler();
}

void yield(void) {
	uint32_t *ICSR = (uint32_t*)0xE000ED04;

	*ICSR |= (1 << 28);
}

void task_delay(uint32_t tick_count) {
	if(current_task) {
		user_tasks[current_task].block_count = g_tick_count + tick_count;
		user_tasks[current_task].current_state = BLOCKED_STATE;
		yield();
	}
}

void SysTick_Init(uint32_t freq) {
	uint32_t *pSYST_RVR = (uint32_t *)0xE000E014;
	uint32_t *pSYST_CSR = (uint32_t *)0xE000E010;
	uint32_t reloadValue = SYSTICK_CLK / freq - 1;

	// Clear data
	*pSYST_RVR &= ~(0x00FFFFFF);
	// Load reload value
	*pSYST_RVR = reloadValue;
	*pSYST_CSR |= (1 << 1);
	*pSYST_CSR |= (1 << 2);
	*pSYST_CSR |= (1 << 0);

}

void enable_processor_fault() {
	uint32_t *SHCSR = (uint32_t*)0xE000ED24;

	*SHCSR |= (1 << 16);
	*SHCSR |= (1 << 17);
	*SHCSR |= (1 << 18);

}

uint32_t get_psp_value(void) {
	TCB_t *task;
	task = OsHeapPeek(&taskQueue);
	return task->psp_value;
}

__attribute__((naked)) void switch_sp_to_psp(void) {
	//init psp with task1 stack start
	__asm volatile ("PUSH {LR}"); //save LR to main function
	__asm volatile ("BL get_psp_value"); //this call corrupts LR
	__asm volatile ("MSR PSP,R0"); // init psp
	__asm volatile ("POP {LR}"); // get main() LR back

	// change sp to psp
	__asm volatile ("MOV R0,#0x02");
	__asm volatile ("MSR CONTROL,R0");
	__asm volatile ("BX LR");
}

void save_psp_value(uint32_t current_psp_value) {
	TCB_t *task;
	task = OsHeapPeek(&taskQueue);
	task->psp_value = current_psp_value;
}

void update_next_task(void) {
	int state = BLOCKED_STATE;
	TCB_t *task;

	task = OsHeapExtract(&taskQueue);
	OsHeapInsert(&taskQueue, task);

//	for(int i = 0; i < numberCreatedTask; i++) {
//		current_task++;
//		current_task %= numberCreatedTask;
//		state = user_tasks[current_task].current_state;
//		if((state == RUNNING_STATE) && (current_task != 0))
//			break;
//	}
//
//	if(state != RUNNING_STATE)
//		current_task = 0;
}

void unblock_tasks(void) {
	for(int i = 1; i < MAX_TASKS; i++) {
		if (user_tasks[i].current_state != RUNNING_STATE) {
			if (user_tasks[i].block_count == g_tick_count) {
				user_tasks[i].current_state = RUNNING_STATE;
			}
		}
	}
}

void SysTick_Handler(void) {
	g_tick_count++;
	unblock_tasks();
	yield();
}

__attribute__((naked)) void PendSV_Handler(void) {
	// save the context of current task
	__asm volatile ("MRS R0,PSP"); //get current task's psp
	__asm volatile ("STMDB R0!,{R4-R11}"); // using psp store sf2 (r4-r11)
	__asm volatile ("PUSH {LR}");
	__asm volatile ("BL save_psp_value");

	// retrieve the context of the next task
	__asm volatile ("BL update_next_task");//select next task
	__asm volatile ("BL get_psp_value"); // get next task's psp
	__asm volatile ("LDMIA R0!,{R4-R11}"); // retrieve R4-r11
	__asm volatile ("MSR PSP,R0");
	__asm volatile ("POP {LR}");
	__asm volatile ("BX LR");
}

void delay(uint32_t count) {
	for(uint32_t i = 0; i < count; i++);
}

void HardFault_Handler(void) {
	printf("Exception: Hardfault\n");
	while(1);
}

void MemManage_Handler(void) {
	printf("Exception: MemFault\n");
	while(1);
}

void BusFault_Handler(void) {
	printf("Exception: BusFault\n");
	while(1);
}












